### PR TITLE
`PSFConvolvedModel2D` and Upgrades to Modeling

### LINKED ISSUE #20: plot_fit for needs the model to have x_0, y_0 attributes
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-157-e7716bae40d5> in <module>
----> 1 plot_fit(target_zoom_raw_image, fitted_psf_model, vmax=vmax, vmin=vmin);

/media/robel/project/lcbg/petrofit/petrofit/fitting/utils.py in plot_fit(image, model, vmin, vmax)
     35         x_0, y_0 = [i.value for i in [model.x_mean, model.y_mean]]
     36     else:
---> 37         x_0, y_0 = model.x_0, model.y_0  # Center
     38 
     39     if isinstance(x_0, Parameter):

AttributeError: 'PSFModel' object has no attribute 'x_0'


```

### LINKED ISSUE #55: Rename `PSFModel` to `PSFConvolvedModel2D`
Based on user feedback, it would make it more clear to rename the `PSFModel` class to `PSFConvolvedImageModel`.  This is because there is a model called `PSFModel` in Photutils and it may be confusing for users.  

CC: @eteq

### LINKED ISSUE #57: Upgrade PSFModel class
Currently the PSFModel class is a wrapper, we should make it an AstroPy model before contributing it to upstream packages.

### LINKED ISSUE #87: Fitting Weights
Implement weights for fitting. This is as easy as exposing the AstroPy `weights` parameter by adding it to `petrofit.fitting.fit_model` (i.e `fit_model(... , weights=None)`)

### LINKED ISSUE #99: Move `fitting.py` and `models.py` into `modeling` folder
We should follow AstroPy and put all modeling related functions into a `modeling` folder. Users can then import things like:

```
from petrofit.modeling import models 
from petrofit.modeling import model_to_image, print_model_params # etc... 
```

~~Should also move the general code into a `core.py` file.~~

### LINKED ISSUE #105: Reverse `model_to_image` size input from `(y, x) -> (x, y)`
#101 revered the size input to match numpy but this is probably more confusing than it is useful. Reverse this order to help with clarity. In the future we can use `shape` instead.

### LINKED ISSUE #106: Add Override `dict` from `get_default_sersic_bounds`
Allow users to override the default bounds during function call by adding an argument to the function. The user can then provide a dict to override the values.

### PR DESCRIPTION
**Pull request by robelgeda**
Enhancements:
close #57
close #55
close #99

Bug fixes:
fixes #20
fixes #87
fixes #105
fixes #106

This PR introduces upgrades to and deprecates the `PSFModel` class by introducing the `PSFConvolvedModel2D` class (model). This PR also moves the fitting code to a modeling folder according to #99. Deprecation warning has been added to `PSFModel` but it has not been removed. I will be removed in the next version of the code (likely `v0.5`, see ticket #102).

For #87, I exposed the Astropy weights parameter in `petrofit.modeling.fitting.fit_model` so users can pass fitting weights using rms images. I have added this to the docs as well.

- [x]  Docstrings
- [x]  Docs and examples
- [x]  petrofit_notebooks
- [x]  Tests

### CODE REVIEW

**Comment by robelgeda** [comment]
Reminder to push changes to `petrofit_notebooks`

**Comment by robelgeda** [comment]
To save time, I have added #87 and #105 to this PR

**Comment by crawfordsm** [comment]
I've taken a look and run through the code.  I'm able to reproduce the notebooks, and I like leaving the PSFModel in there for the time being but with the deprecation warning. Setting up the infrastructure to follow the astropy directory structrue make sense and hopefully will make it easier to move some things upstream

**Review by crawfordsm — APPROVED** [review]

**Comment by robelgeda** [comment]
Thank you @crawfordsm! I will merge once tests pass. Also I did a minor last minute update, I renamed `PSFConvolvedImageModel -> PSFConvolvedModel2D` because we may in the future make a 1D version of this class. I will open a ticket as a reminder.

**Pull request merged**
